language: android

sudo: false

branches:
  only: master

script: gradle :demo:assembleRelease

android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.1
    - android-23

    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository
    - sys-img-armeabi-v7a-android-19
    - sys-img-x86-android-17

    after_success:
      # run bintray upload straight after deploy
      - gradle bintrayUpload -PbintrayUser=$USER -PbintrayKey=$KEY -PdryRun=false
